# Generated by Django 3.2 on 2021-04-13 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=150)),
                ('app_type', models.CharField(max_length=25)),
                ('app_description', models.TextField()),
                ('affiliate_url', models.SlugField(blank=True, null=True)),
                ('app_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
