# Generated by Django 3.2 on 2021-04-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_popularity_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularity_model',
            name='model_name',
        ),
    ]
