# Generated by Django 3.2 on 2021-04-14 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
